# Generated by Django 3.0.7 on 2020-07-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('obstime', models.DateTimeField(primary_key=True, serialize=False)),
                ('tempr', models.FloatField()),
                ('ap', models.FloatField()),
                ('ws', models.FloatField()),
                ('wd', models.FloatField()),
                ('rh', models.FloatField()),
                ('blizzard', models.FloatField(null=True)),
            ],
        ),
    ]
